#include "Leg.hpp"
#include <ModernRobotics>

// Forward Kinematics
void Leg::fk() {
  double th1 = thetalist[0];
  double th2 = thetalist[1];
  double th3 = -thetalist[2] - thetalist[1];
  double h = l[1] * sin(th2) + l[2] * sin(th3);
  double s1 = sin(th1);
  double c1 = cos(th1);

  pf.x() = -l[1] * cos(th2) + l[2] * cos(th3);
  pf.y() = l[0] * c1 - h * s1;
  pf.z() = l[0] * s1 + h * c1 + l[3];
}

// Inverse Kinematics
bool Leg::ik() {
  /* Inverse Kinematics */
  double x = pf.x();
  double y = pf.y();
  double z = pf.z() - l[3];
  double zproj = sqrt(pow(z, 2) + pow(y, 2) -
                      pow(l[0], 2)); // z projection on plane of upper/lower leg
  double d2 = pow(x, 2) + pow(zproj, 2);

  if (d2 < 0)
    return false;

  thetalist[0] = atan2(z, y) - acos(l[0] / sqrt(y * y + z * z));
  thetalist[1] = atan2(zproj, x) - acos((pow(l[1], 2) + d2 - pow(l[2], 2)) /
                                        (2.0 * l[1] * sqrt(d2)));
  thetalist[2] =
      -acos((pow(l[1], 2) + pow(l[2], 2) - d2) / (2.0 * l[1] * l[2]));
  thetalist = thetalist.cwiseProduct(thetadir);

  /* Inverse Velocity Kinematics */

  // Leg Jacobian Inverse
  // Generated by SymPy, optimized by hand
  double xmult1 = -l[0] / (pow(pow(y, 2) + pow(z, 2), 1.5) *
                           sqrt(-pow(l[0], 2) / (pow(y, 2) + pow(z, 2)) + 1.0));
  double xmult2 = 1.0 / (pow(y, 2) + pow(z, 2));
  double ymult =
      (1.0 / (sqrt(d2) * l[1]) -
       0.5 * (d2 + pow(l[1], 2) - pow(l[2], 2)) / (pow(d2, 1.5) * l[1])) /
      sqrt(1 - 0.25 * pow(d2 + pow(l[1], 2) - pow(l[2], 2), 2) /
                   (d2 * pow(l[1], 2)));
  double zmult =
      -1.0 / (l[1] * l[2] *
              sqrt(1.0 - 0.25 * pow(-d2 + pow(l[1], 2) + pow(l[2], 2), 2) /
                             (pow(l[1], 2) * pow(l[2], 2))));

  Jinv(0, 0) = 0.0;
  Jinv(0, 1) = y * xmult1 - z * xmult2;
  Jinv(0, 2) = z * xmult1 + y * xmult2;
  Jinv(1, 0) = x * ymult - zproj / d2;
  Jinv(1, 1) = y * ymult + x * y / (d2 * zproj);
  Jinv(1, 2) = z * ymult + x * z / (d2 * zproj);
  Jinv(2, 0) = x * zmult;
  Jinv(2, 1) = y * zmult;
  Jinv(2, 2) = z * zmult;
  Jinv *= thetadir.asDiagonal();

  dthetalist = Jinv * vf;
  return true;
}

void Leg::id() {
  Mi = Eigen::Isometry3d::Identity();
  Vi.col(0).setZero();
  dVi.col(0) << Eigen::Vector3d::Zero(), -g;
  AdTi[njoints] = Ad(Mlist[njoints].inverse());
  Fi << Eigen::Vector3d::Zero(), ffoot;

  // forward pass
  for (int i = 0; i < njoints; i++) {
    Mi = Mi * Mlist[i];
    Ai.col(i) = Ad(Mi.inverse()) * Slist.col(i);
    AdTi[i] = Ad(exp(se3(Ai.col(i) * -thetalist(i))) * Mlist[i].inverse());
    Vi.col(i + 1) = AdTi[i] * Vi.col(i) + Ai.col(i) * dthetalist(i);
    dVi.col(i + 1) = AdTi[i] * dVi.col(i) + Ai.col(i) * ddthetalist(i) +
                     ad(Vi.col(i + 1)) * Ai.col(i) * dthetalist(i);
  }

  // backward pass
  for (int i = njoints - 1; i >= 0; i--) {
    Fi = AdTi[i + 1].transpose() * Fi + Glist[i] * dVi.col(i + 1) -
         ad(Vi.col(i + 1)).transpose() * (Glist[i] * Vi.col(i + 1));
    taulist(i) = Fi.transpose() * Ai.col(i);
  }
}

void Leg::run() {
  ik();
  id();
}

// void Leg::home() {
//   fmts[0] = fmt_home;
//   fmts[1] = fmt_home;
//   fmts[2] = fmt_home;
//   cmds[0] = PosCmd{};
//   cmds[1] = PosCmd{};
//   cmds[2] = cmd_home;
// }

// void Leg::walk(const Eigen::Vector3d &v, useconds_t dt) {
//   Eigen::Vector3d v_copy = v;
//   v_copy.z() = 0; // ignore vertical velocity for now
//   Eigen::Vector3d dp = Eigen::Vector3d::Zero();
//   double dt_sec = dt * 1e-6; // convert to seconds

//   // Modify state based on position
//   if (v_copy.squaredNorm() < v_min * v_min)
//     state = IDLE;
//   switch (state) {
//   case IDLE: {
//     if (v_copy.squaredNorm() > v_min * v_min) {
//       state = TRAVEL;
//     }
//   } break;
//   case TRAVEL: {
//     if ((p - home_pos).squaredNorm() > travel[1]) {
//       state = LIFT;
//     }
//   } break;
//   }

//   // Calculate change in position based on state
//   switch (state) {
//   case IDLE: {
//     p = home_pos + Eigen::Vector3d(travel * 3 / 5 * legNum - travel, 0, 0);
//   } break;
//   case TRAVEL: {
//     dp = v_copy * dt_sec;
//   } break;
//   case LIFT: {
//     p = lift_pos;
//     // p.z() = lift_height * cos(M_PI_2 * p.head<2>().norm() / travel);
//   } break;
//   case PLACE: {
//     p = -v_copy.normalized() * travel * 0.98 + home_pos;
//   }
//   }

//   p += dp;
//   // t += dt;
//   // p = f();

//   ik(p, theta);
// }

// Eigen::Vector3d Leg::f() {
//   // Given time t that goes from 0 to 1
//   double phase = fmod(t / 1e6, 1.0);

//   // If t is in the first half of the cycle, interpolate from home_pos to
//   // lift_pos
//   if (phase < 0.5) {
//     double alpha = phase / 0.5; // Normalize to [0, 1]
//     return home_pos * (1 - alpha) + lift_pos * alpha;
//   }
//   // If t is in the second half of the cycle, interpolate from lift_pos to
//   // home_pos
//   else {
//     double alpha = (phase - 0.5) / 0.5; // Normalize to [0, 1]
//     return lift_pos * (1 - alpha) + home_pos * alpha;
//   }
// }